//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Kho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUAT()
        {
            this.CTPHIEUXUATs = new HashSet<CTPHIEUXUAT>();
        }
    
        public string MaPX { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string MaKH { get; set; }
        public string DiaChi { get; set; }
        public string MaNV { get; set; }
        public string MaKho { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUXUAT> CTPHIEUXUATs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
